##################################
# Required GitHub secrets:
#   - CODECOV_TOKEN
##################################

name: ci
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn format:check

      - name: Run tests & coverage
        run: yarn test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Node v${{ matrix.node-version }}

